In [1]:
import numpy as np

costs = [[24,50,5,27,16],
         [50,47,23,17,21],
         [35,59,55,27,41]]
supply = [200,350,300]
demand = [270,130,190,150,110]

#Ініціалізація матриці розподілення
allocation = np.zeros((len(supply), len(demand)))

#Ініціалізація індексів для запасів та потреб
i, j = 0, 0

#Ітерувати поки умова не буде задовільнена
while i < len(supply) and j < len(demand):
    #Вирахувати можливий розподіл
    quantity = min(supply[i], demand[j])
    
    #Оновлення матриці
    allocation[i, j] = quantity
    
    #Оновлення запасів та потреб
    supply[i] -= quantity
    demand[j] -= quantity
    
    #Перехід далі при задоволенні умов
    if supply[i] == 0:
        i += 1
    if demand[j] == 0:
        j += 1

#Виведення результатів
print("Allocation Matrix:")
print(allocation)

Allocation Matrix:
[[200.   0.   0.   0.   0.]
 [ 70. 130. 150.   0.   0.]
 [  0.   0.  40. 150. 110.]]


In [5]:
from scipy.optimize import linear_sum_assignment
import numpy as np

#Дані задачі
supply = [310, 260, 280, 360, 220]  
demand = [170, 200, 180, 210, 240, 180, 250]  

cost_matrix = [
    [10, 15, 20, 5, 8, 22, 18],   
    [12, 14, 10, 7, 13, 15, 11],  
    [16, 11, 8, 9, 17, 20, 14],   
    [19, 8, 14, 16, 10, 18, 12],   
    [22, 10, 13, 12, 11, 17, 9]    
]

#Розв'язання транспортної задачі методом потенціалів
cost_matrix_np = np.array(cost_matrix)
row_ind, col_ind = linear_sum_assignment(cost_matrix_np)

#Вивід результатів
print("Оптимальний план перевезення:")
for i, j in zip(row_ind, col_ind):
    print(f"Завод {i + 1} -> Склад {j + 1}")


Оптимальний план перевезення:
Завод 1 -> Склад 5
Завод 2 -> Склад 4
Завод 3 -> Склад 3
Завод 4 -> Склад 2
Завод 5 -> Склад 7
